version: '3'
services:
  service:
    image: crpi-ldcb2d9ge4cmfxso.cn-hangzhou.personal.cr.aliyuncs.com/sirius-hub/hub:latest
    ports:
    volumes:
      - ./config.json:/app/config.json
      - ./log:/app/log/
    network_mode: "host" 